:email: mail@su363.ru
:phone: +7 (495) 363-65-82
:address:
  :text: 115409, г.&nbsp;Москва, Каширское&nbsp;шоссе, д.&nbsp;50, корп.&nbsp;2А
  :url: https://clck.ru/EScbc
:geo:
  :latitude: 55.646035
  :longitude: 37.666438
...
